# OpenAI
api_key: ""
model: "gpt-4o"
parser_model: "gpt-4o-mini"
temperature: 0.0

# Robust Mode
RobustMode: True

# Error Handling
SleepTime: 3 # sleep time between API calls (in seconds), to prevent TPM rate limit.
RetryMultiplier: 1
RetryMinimum: 4
RetryMaximum: 10

# Prompt
prompt_file_path: "prompt.yaml"

# Input - Output
pdf_input_files_folder: "pdf_papers"
plain_text_input_files_folder: "markdown_files"
output_files_folder: "output"
logger_output_folder: "logs"
