# OpenAI
api_key: ""
model: "gpt-4o"
parser_model: "gpt-4o-mini"
temperature: 0.0

# Robust Mode
RobustMode: True

# Error Handling
SleepTime: 3 # sleep time between API calls (in seconds), to prevent TPM rate limit.
RetryMultiplier: 1
RetryMinimum: 4
RetryMaximum: 10

# Prompt
prompt_file_path: "prompt.yaml"

# CSV Entry Predefined Header
CSVEntryHeader: "no, file_name, criteria 1.1, criteria 1.2, criteria 1.3, criteria 1.4, criteria 1.5, criteria 2.1, criteria 2.3, criteria 2.4, criteria 2.5, criteria 2.6, criteria 5.1, criteria 6.1, criteria 6.2, criteria 6.3, criteria 7.1, criteria 7.2, criteria 7.3, criteria 7.4"

# Input - Output
pdf_input_files_folder: "pdf_papers"
plain_text_input_files_folder: "markdown_files"
output_files_folder: "output"
logger_output_folder: "logs"